# Nested exceptions

Write a Python function called `nested_exceptions(tree)` that, given a tree of functions in the form of nested tuples `tree` where each element is a function, returns a tree with the same structure containing `True` if the function raises an exception or `False` otherwise.


Hint: You can use the built-in [`callable()`](https://docs.python.org/3/library/functions.html) to see if an object is a function or not.



## Private Tests [100%]

## Public Tests [100%]
